### ISSUE TITLE
Serial port detection/connection failure

### ISSUE THREAD

**Issue by darksweet** [dennisppaul/klangstrom-arduino#1]
I got the Klang TINY working for a while last night and uploading new programs was successful. But at some point, the USB connection couldn't get recognized anymore. 
Currently, no blinking led after pressing the program button. I also tried detecting it with my friend's mac, but so far no luck on getting a detection. 
Maybe it's because I tried the reset and reboot button. Is there a way to "factory reset" the TINY board?

**Comment by darksweet** [comment]
> I got the Klang TINY working for a while last night and uploading new programs was successful. But at some point, the USB connection couldn't get recognized anymore.
> Currently, no blinking led after pressing the program button. I also tried detecting it with my friend's mac, but so far no luck on getting a detection.
> Maybe it's because I tried the reset and reboot button. Is there a way to "factory reset" the TINY board?

BTW, I'm using MAC (macOS Mojave Version 10.14.6(18G103))

**Comment by dennisppaul** [comment]
i will look into it. in the meantime you can make the board enter DFU mode by pressing `BOOT` + `RESET` then letting go of `RESET` and shortly after of `BOOT`. now the board should have entered DFU mode. because the buttons are very small it might take more than one try at first.

**Comment by dennisppaul** [comment]
fixed issues. there was a problem with USB not being de-initialized which prevent entering DFU mode.
